### ISSUE TITLE
Parameter startAt does not work with PDF files

### ISSUE THREAD

**Issue by EmmanuelCarrara** [box/box-content-preview#1079]
**Environment:**
- Preview version: 2.21.0

**Desktop (please complete the following information):**
 - OS: Windows 10 x64
 - Browser Chrome
 - Version 77.0.3865.90

**Steps to reproduce the problem:**
1. Try to preview a specific page on a PDF file specifing the 'startAt' parameter

**What is the expected behavior? (Screenshots can be helpful here)**
The document should open on the page specified

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**
The document opened on the first page

**Additional context**
The same code works correctly to display a specific page on a DOCX file.

**Comment by jstoffan** [comment]
Hi @EmmanuelCarrara. I'm not able to reproduce this issue on 2.21.0. Note that the `startAt` option requires a very specific format, shown in the example code below:

```
preview.show(1234567890, TOKEN, {
    fileOptions: {
        1234567890: {
            startAt: {
                unit: 'pages',
                value: 2
            }
        }
});
```

Can you include a code snippet demonstrating the problem, as you see it? It's very helpful for us during troubleshooting, which is why we request it in our issue template. Thanks.

**Comment by EmmanuelCarrara** [comment]
After modifying how the parameter is built, it worked! 
Could you add the example to the documentation, please?
Thank you very much!
