### ISSUE TITLE
"Press down" is not required in annotation Draw mode.

### ISSUE THREAD

**Issue by m-nakamura145** [box/box-content-preview#1393]
**Environment:**
- Preview version: latest version(v2.74.0)

**Desktop (please complete the following information):**
 - OS: Mac OS 11.4 Big Sur
 - Browser 
   - Chrome Version 90.0.4430.212 (Official Build) (x86_64)
   - Safari Version 14.1.1 (16611.2.7.1.4)

**Steps to reproduce the problem:**
1. Enable showAnnotations option in ContentExplorer
2. Preview a PDF file.
3. Click "Drawing annotation mode"

**What is the expected behavior? (Screenshots can be helpful here)**
Annotations can be created by simply dragging the pointer. Press Down in the message is not necessary. Is my understanding correct?

**What went wrong? (Screenshots, console logs, or HAR files can be helpful here)**

I think the Press Down in the message is not necessary.

**Expected behavior**
I think the correct message is "Drag the pointer to draw on the document".

**Screenshots**
<img width="1473" alt="Screen Shot 2021-05-28 at 16 05 12" src="https://user-images.githubusercontent.com/11944718/119945685-bffc0700-bfd0-11eb-8bae-23d848b48ff9.png">

**Comment by ConradJChan** [comment]
Hi @m-nakamura145, thanks for your ticket. 

Some initial thoughts are that "Press down" might have been included because drag alone might be ambiguous to some users. Also that this is the legacy annotations codebase and is not actively maintained unless there is a critical bug that needs to be addressed.

This also seems more appropriate for the [box-annotations](https://github.com/box/box-annotations) repository. Please reopen the ticket there if you feel it is necessary.
