### ISSUE TITLE
Preview toolbar

### ISSUE THREAD

**Issue by ovvn** [box/box-content-preview#573]
Got a couple of questions:
1. Can the toolbar (which appears on hover over the content)
<img width="286" alt="localhost_3000_u_0_v3_negotiation_192912aa-423c-4e05-9bde-ed909d79f42a_materials_instructions1" src="https://user-images.githubusercontent.com/2973998/34676782-0a32097e-f49f-11e7-9e06-2e74a5d5724f.png"> 
be moved to top next to the 'print' & 'download' buttons?

2. Can the 'print' button be removed? I can remove it using css but was looking for a more general solution.

**Comment by jeremypress** [comment]
1. If all you want to do is reposition the controls but not change their behavior, then this can be done with CSS (take a look at [Controls.scss](https://github.com/box/box-content-preview/blob/master/src/lib/Controls.scss). Otherwise the easiest way to override the controls would be to fork preview and override the [class](https://github.com/box/box-content-preview/blob/master/src/lib/Controls.js). This will allow you to implement any custom behavior you're looking for. It's likely that you won't have to make changes outside of controls.js, so this should be relatively straightforward to maintain as a fork. Feel free to contact us for more guidance if you go down this route.

2. The best option is to use CSS since we combine both printing and download UI. Another option is to make changes to Preview.js, but this would be more annoying to maintain as this is changed on a semi-regular basis.

**Comment by ovvn** [comment]
Thank you @jeremypress, will try overriding CSS first. Considering combining download and printing UI, it looks it would be better to have separate flags, e.g. `showDownload` and `showPrinting` respectively.

**Comment by jeremypress** [comment]
I agree that this would be cleaner, but due to the fact that this is a backwards incompatible change and is easily solved with CSS, it is unlikely that we will add this flag unless there is a strong demand from our developer base.
